#!/bin/bash
pip install http://download.electrum.org/download/Electrum-1.7.3.tar.gz#md5=22a35b0816f7c6c59fbeddb50e832ada

repoexist=$(cat /etc/apt/sources.list | grep apt.bitcoins.sk | wc -l)
if [ "$repoexist" -gt "0" ]
then
	echo "apt.bitcoins.sk repository already installed"
else
	echo "installing apt.bitcoins.sk repository"
	gpg --keyserver pgp.mit.edu --recv-keys F4E4F580
	gpg -a --export F4E4F580 | apt-key add -
	apt-add-repository 'http://apt.bitcoins.sk/ main'
fi
cp /etc/apt/sources.list /tmp/sources.list.bak
sed '/deb-src http:\/\/apt.bitcoins.sk\//d' /tmp/sources.list.bak > /etc/apt/sources.list


